language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# coverage testing preperation
before_install:
  - pip install codecov
  - pip install pytest pytest-cov
# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - pytest --cov=./
# coverage testing
after_success:
- codecov
