version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: make build && make install && pip install pytest
  test:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: pytest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
